openapi: 3.0.0
info:
  version: "1.0.0"
  title: TP1 - DNS over HTTPS
  description: Documentación del TP1 de la materia 75.43 Introducción a Sistemas Distribuidos

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
  /domains/{domain}:
    get:
      operationId: "api.domains.get_ip"
      tags:
        - "Domains"
      summary: "Obtención de IP de un dominio espeficifado"
      description: "Obtiene la IP asociada a un dominio en particular, con este pudiedno ser un custom domain creado anteriormnente"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El dominio del cual se quiere obtener una IP
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "Dominio no encontrado"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /custom-domains:
    post:
      operationId: "api.domains.create_domain"
      tags:
        - "Domains"
      summary: "Alta de un custom domain en el sistema"
      description: "Crea una entrada para sobreescribir la IP de un dominio en particular"
      requestBody:
        required: true
        x-body-name: 'domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
      responses:
        201:
          description: "Se creo el custom domain correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        400:
          description: "Custom domain duplicado o request mal formado"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
    put:
      operationId: "api.domains.override_domain"
      tags:
        - "Domains"
      summary: "Update de una entrada de un dominio custom"
      description: "Pisa una entrada para un determinado dominio con una ip enviada en el payload del llamado."
      requestBody:
        required: true
        x-body-name: 'domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
      responses:
        200:
          description: "Se creo el custom domain correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        400:
          description: "Custom domain malformado"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
        404:
          description: "Custom domain no existente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

# Declaración de tipos de datos
components:
  schemas:
    Domain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    Error:
      type: "object"
      properties:
        codigo:
          type: "number"
    Input:
      type: "object"
      properties: 
        domain:
          type: "string"
        ip:
          type: "string"
